# Generated by Django 4.2.4 on 2023-08-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_session_box_session_box_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='box_matrix',
            field=models.JSONField(blank=True, help_text='The current box at its latest state', null=True, verbose_name='Box'),
        ),
    ]
